name: SaraUnplugged
favicon: null
layout_spectrum: 0.49211793881841004
typography_spectrum: 0.5537484777159989
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6548263342119753
  lightness: 0.6011999770998955
  saturation: 0.8423732379451394
  rhythmicContrast: 0.6384048636537045
purpose: []
