name: SaraUnplugged
favicon: null
layout_spectrum: 0
typography_spectrum: 0.03358
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7e3000'
    - '#c27b11'
    - '#120806'
    - '#caccc7'
    - '#93948e'
  brandStrength: 0.3125
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
